Tweak opening, fix spelling in about.md
exercism/elm pull request #419
Opened 2021-09-11 14:53 UTC by rerb

1. Make intro friendlier.
2. Fix spelling of “privately”.

2021-09-11 15:06 UTC, mpizenberg requested changes
Thanks for the typo and the wording, I like it very much! (with a small nitpick change)
What do you think @ceddlyburge ?

2021-09-11 15:06 UTC, mpizenberg commented on concepts/basics-1/about.md
> +Elm programs are composed of definitions and expressions.  Everything in Elm is either a definition or expression.
```suggestion
Elm programs are composed of definitions and expressions. Everything in Elm is either a definition or an expression.
```

2021-09-11 21:29 UTC, ceddlyburge commented
Yep, I agree, this is a good change.

On Sat, 11 Sep 2021, 16:06 Matthieu Pizenberg, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks for the typo and the wording, I like it very much! (with a small
> nitpick change)
> What do you think @ceddlyburge <https://github.com/ceddlyburge> ?
> ------------------------------
>
> In concepts/basics-1/about.md
> <https://github.com/exercism/elm/pull/419#discussion_r706623515>:
>
> > @@ -2,8 +2,9 @@
>
>
>
>  ## Constants and functions
>
>
>
> -A constant value is defined with `name = expression`,
>
> -where in Elm, everything except definitions are expressions.
>
> +Elm programs are composed of definitions and expressions.  Everything in Elm is either a definition or expression.
>
>
> ⬇️ Suggested change
>
> -Elm programs are composed of definitions and expressions.  Everything in Elm is either a definition or expression.
>
> +Elm programs are composed of definitions and expressions. Everything in Elm is either a definition or an expression.
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/exercism/elm/pull/419#pullrequestreview-751925120>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADHR5R4DLVKUUV2KHED4SQTUBNWABANCNFSM5D3BE6OQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-12 00:15 UTC, mpizenberg approved these changes

2021-09-12 00:15 UTC, merged