corrected wrong test case
exercism/elm pull request #565
Opened 2023-04-07 14:25 UTC by debanwita27

"Casting a spell spends double the mana" 
mana = 20 and manaCost = 9
updated mana should be 20 - 2*9 = 20 - 18 = 2
test case given : 11(wrong)

2023-04-07 22:35 UTC, ceddlyburge commented
Hi Debanwita, I think the test is correct actually.

The instructions state that the damage done is double the mana cost, not that the mana cost is doubled.

The name of the test looks wrong though, how about we change it from 
`"Casting a spell spends double the mana"`
to 
`"Casting a spell causes damage of double the mana"'?

2023-04-07 22:37 UTC, ceddlyburge requested changes

2023-04-07 22:37 UTC, ceddlyburge commented on exercises/concept/role-playing-game/tests/Tests.elm
>              [ test "Casting a spell spends double the mana" <|
```suggestion
            [ test "Casting a spell causes damage of double the mana" <|
```

2023-04-07 22:37 UTC, ceddlyburge commented on exercises/concept/role-playing-game/tests/Tests.elm
> +                        ( { name = Nothing, level = 10, health = 69, mana = Just 2 }, 18 )
```suggestion
                        ( { name = Nothing, level = 10, health = 69, mana = Just 11 }, 18 )
```

2023-04-08 09:01 UTC, mpizenberg commented
Indeed, the test is correct, but the test wording is wrong. I like the new wording by @ceddlyburge better too.

2023-04-08 14:10 UTC, debanwita27 commented
The initial wording made me misunderstand the case. Thanks for the explanation :D

2023-04-08 14:11 UTC, ceddlyburge approved these changes

2023-04-08 14:11 UTC, merged

2023-04-08 21:11 UTC, ceddlyburge commented
Yep, thanks for spotting the problem and bringing it to our attention :)